### ISSUE TITLE
Link to the Youtube video explaining it all

### ISSUE THREAD

**Issue by xandark** [blondie7575/HiSprite#6]
I've been following this project through the KansasFest 2017 videos and this project answers a lot of questions I've had about Apple II HGR sprite-compiling. 

For the others who are looking for this information and your hard-won experience, could your project Readme file have a link to the video so that others can see your process and your conclusions? This is the video I'm thinking of:

https://www.youtube.com/watch?v=byVvMsW__Cc

Above and beyond that, any comments on the Python sprite generator would be great too.

**Comment by blondie7575** [comment]
Great ideas, thanks! Will do.
